db.createUser(
    {
        user:"root",
        password:"rootpassword",
        roles:[
            {
                role:"readWriteAnyDatabase",
                db:"admin"    
            }
        ]
    }
)
